### ISSUE TITLE
How to add build.rs to a package

### ISSUE THREAD

**Issue by 0x143** [extendr/rextendr#339]
Hi. I noticed that I have to add build file explicitly to my `Cargo.toml` file: 

```toml
[package]
#  ...
build = "build.rs"
# ...
```

for it to be detected and executed. 

It made me wonder if there is any reason to avoid it in the first place.
