### ISSUE TITLE
[TOML] Add a line break between tables

### ISSUE THREAD

**Issue by yutannihilation** [extendr/rextendr#55]
This is the TOML file generated by `rextendr::use_extendr()`.

```toml
[package]
name = 'helloextendr'
version = '0.1.0'
edition = '2018'
[lib]
crate-type = [ 'staticlib' ]
[dependencies]
extendr-api = '*'
```

This might be just my preference, but I think it's more readable if there's an empty line between tables.

```toml
[package]
name = 'helloextendr'
version = '0.1.0'
edition = '2018'

[lib]
crate-type = [ 'staticlib' ]

[dependencies]
extendr-api = '*'
```

This can be done by concatenating each table to a single string, instead of flattening them. Here's my naive attempt (note that array of tables needs a bit more tweak):

https://github.com/yutannihilation/rextendr/commit/12611cd5455e90f79b09b84d0133c6bd8cff2afc
